---

- name: setup pacman.conf
  sudo: yes
  ini_file: 
    dest: '{{ pacman_conf }}'
    section: options
    option: '{{ item.key }}'
    value: '{{ item.value }}'
  with_dict: pacman_options
  notify: Sync pacman

- name: use your arch package mirrors
  sudo: yes
  lineinfile: 
    dest: '{{ pacman_mirrorlist }}'
    insertbefore: BOF
    regexp: ^Server = {{ item.replace('$', '.') }}
    line: Server = {{ item }}$repo/os/$arch
  with_items: pacman_mirrors
  notify: Sync pacman

- name: upload pacman trustdb and pubring
  copy: src=/etc/pacman.d/gnupg/{{ item }}.gpg dest=.
  register: pacman_key_upload
  with_items: [pubring, trustdb]

- name: impor thrustdb into pacman
  shell: pacman-key --import .
  sudo: yes
  when: pacman_key_upload.changed

- name: add your repositories
  sudo: yes
  ini_file: 
    dest: '{{ pacman_conf }}'
    section: '{{ item.name }}'
    option: Server
    value: '{{ item.url }}'
    backup: yes
  with_items: pacman_repositories
  notify: Sync pacman

- meta: flush_handlers
